### ISSUE TITLE
Some links in README are broken

### ISSUE THREAD

**Issue by ottis** [quantumblacklabs/causalnex#1]
## Description

Firstly congrats on open sourcing this project, awesome work everyone! 🙂 Just a quick issue, seems like there is some broken links on the README for the tutorial section.

## Steps to Reproduce
1. Go to README
2. Click on link in "An end-to-end tutorial on how to use CausalNex" or "The main concepts and methods in using Bayesian Networks for Causal Inference"

## Expected Result

Loads correct tutorial page

## Actual Result

404

**Comment by wesleyleong** [comment]
Thank you @ottis for your feedback - we would look to fix this asap!

**Comment by ZainPatelQB** [comment]
Fixed by #2?

**Comment by wesleyleong** [comment]
Yep!
> Fixed by #2?

**Comment by ZainPatelQB** [comment]
> Yep!
> 
> > Fixed by #2?

Can close then! :)
