### ISSUE TITLE
Question about NonLinear DAGRegressor: How does the nonlinear model of perceptrons fit into the larger structural model?

### ISSUE THREAD

**Issue by nick-gorman** [quantumblacklabs/causalnex#101]
Suppose after running the NonLinear DAGRegressor we have a model with the structure: a -> c and b -> c. 

Are there two separate sets of perceptrons, and c is equal to the sum of outputs from both. Or is there one set of perceptrons with both a and b as inputs and c equal to the output? Or something else?

**Comment by oentaryorj** [comment]
Hi @nick-gorman, the details can be found in [this paper](http://proceedings.mlr.press/v108/zheng20a/zheng20a.pdf). Based on the paper, the MLP represents a function `f_j(X_pa(j))`, where `pa(j)` denotes the parents of `X_j` in graph `G`. So my understanding the input corresponds to the parent nodes (i.e., "a" and "b" in your case) and the output corresponds to the child node (i.e., "c").

Hope this answers your question. Feel free to open a new issue if you have other enquiries. Thanks.
