### ISSUE TITLE
pip install fails with ERROR: Could not find a version that satisfies the requirement causalnex (from versions: none)

### ISSUE THREAD

**Issue by chanansh** [quantumblacklabs/causalnex#107]
## Description
pip install fails
ERROR: Could not find a version that satisfies the requirement causalnex (from versions: none)

## Context
cannot pip install

## Steps to Reproduce
1. new conda env
2. pip install causalnex
3. error message

## Expected Result
install

## Actual Result
error message

```
-- If you received an error, place it here.
```
hanan@h-MacBook-Pro-sl-Hanan ~/c/t/v> pip install causalnex                                                                                       (causal_python_pycon2021)
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Users/hanan/opt/anaconda3/envs/v/include/python3.9/UNKNOWN
sysconfig: /Users/hanan/opt/anaconda3/envs/v/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
ERROR: Could not find a version that satisfies the requirement causalnex (from versions: none)
ERROR: No matching distribution found for causalnex```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`):
* Python version used (`python -V`):Python 3.9.2
* Operating system and version: macos

**Comment by mzjp2** [comment]
I believe this is because you are using Python 3.9, which CausalNex doesn't currently support (and something we should hop on ASAP - thanks for pointing it out). Can you downgrade to 3.8 in the meantime?

**Comment by qbphilip** [comment]
Hello Dr Hanan, 

We make the package python 3.9 compliant in #111, release 0.10.0
We wont yet fully support it due to an optional dependency issue.

However, basic functionality will work in python 3.9 when you build from source :)

Philip
