### ISSUE TITLE
pandas error

### ISSUE THREAD

**Issue by aminemosbah** [quantumblacklabs/causalnex#11]
tryng to run the model on google collab and pandas rises issues about importing some packages
 the first one that turned out to be fatal is relevent to  'OrderedDict'
code: 
/usr/local/lib/python3.6/dist-packages/pandas/io/formats/html.py in <module>()
      8 from textwrap import dedent
      9 
---> 10 from pandas.compat import OrderedDict, lzip, map, range, u, unichr, zip
     11 
     12 from pandas.core.dtypes.generic import ABCMultiIndex

ImportError: cannot import name 'OrderedDict'

the second one which is fatal is relevant to importing lmap

/usr/local/lib/python3.6/dist-packages/pandas/core/config.py in <module>()
     55 
     56 import pandas.compat as compat
---> 57 from pandas.compat import lmap, map, u
     58 
     59 DeprecatedOption = namedtuple('DeprecatedOption', 'key msg rkey removal_ver')

ImportError: cannot import name 'lmap'

with standalone pandas, I did not get these issues seems to me google collab missing something 
any suggestions please ?

**Comment by benhorsburgh** [comment]
Hi,

Can you please also post the line of code you are trying to execute that causes the errors? If possible, also the output of `pip freeze`. 

Thanks

**Comment by aminemosbah** [comment]
Actually i simply tried to open a plain csv file using
Read csv it worked well in the stand-alone notebook 
I think something went wrong with google collab it s unfortunate because bn is awsome for big data can not just limit its use for cpus

**Comment by aminemosbah** [comment]
here is my code 
data = pd.read_csv('/content/causalnex/fulcase_causal.csv',decimal=',',delimiter=';')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    336             method = get_real_method(obj, self.print_method)
    337             if method is not None:
--> 338                 return method()
    339             return None
    340         else:

2 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/formats/html.py in <module>()
      8 from textwrap import dedent
      9 
---> 10 from pandas.compat import OrderedDict, lzip, map, range, u, unichr, zip
     11 
     12 from pandas.core.dtypes.generic import ABCMultiIndex

ImportError: cannot import name 'OrderedDict'
   Cd  Batch  Weight       HSI         K  ...  TB  SGR  FCR  PER      Ca/P
0   0      0   59.84  0.501337  1.026063  ...   1  0.0  0.0  0.0  1.528497
1   0      0   56.28  0.835110  0.965021  ...   6  0.0  0.0  0.0  1.369458
2   0      0   60.50  1.603306  0.955521  ...   2  0.0  0.0  0.0  1.512605

**Comment by aminemosbah** [comment]
followup

bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    336             method = get_real_method(obj, self.print_method)
    337             if method is not None:
--> 338                 return method()
    339             return None
    340         else:

2 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/formats/html.py in <module>()
      8 from textwrap import dedent
      9 
---> 10 from pandas.compat import OrderedDict, lzip, map, range, u, unichr, zip
     11 
     12 from pandas.core.dtypes.generic import ABCMultiIndex

ImportError: cannot import name 'OrderedDict'
   Cd  Batch  Weight       HSI         K  ...  TB  SGR  FCR  PER      Ca/P
0   0      0   59.84  0.501337  1.026063  ...   1  0.0  0.0  0.0  1.528497
1   0      0   56.28  0.835110  0.965021  ...   6  0.0  0.0  0.0  1.369458
2   0      0   60.50  1.603306  0.955521  ...   2  0.0  0.0  0.0  1.512605
/usr/local/lib/python3.6/dist-packages/pandas/core/config.py in <module>()
     55 
     56 import pandas.compat as compat
---> 57 from pandas.compat import lmap, map, u
     58 
     59 DeprecatedOption = namedtuple('DeprecatedOption', 'key msg rkey removal_ver')

ImportError: cannot import name 'lmap'
any help

**Comment by ZainPatelQB** [comment]
This is really weird, `OrderedDict` is built-in from Python 3. Does this SO article help? https://stackoverflow.com/questions/57328692/pandas-importerror-cannot-import-name-ordereddict-when-i-try-to-read-a-csv-f

**Comment by aminemosbah** [comment]
already tied it  , useless
seems to me something is really off with google collab

**Comment by libinruan** [comment]
google-colab 1.0.0 requires pandas~=0.24.0, so I am wondering if it's the reason that causes the problem.
