### ISSUE TITLE
404 in Documentation links

### ISSUE THREAD

**Issue by huanyi89** [quantumblacklabs/causalnex#113]
Hello 
Thank you for the great package.
I am trying to go through the documentation, and have more understanding of the Bayesian Network that used in this library. However, there some links in the causalnex website is not valid anymore.
I wonder if you can update those links.

The two I was trying to access are
1. You can find news about updates and new features introduced by heading over to _**RELEASE.md.**_

2. Where can I learn more about Bayesian Networks?
    You can read our _**documentation**_ to know more about the concepts and other useful references 
    with regards to using Bayesian Networks for Causal Inference.

Thank you

**Comment by oentaryorj** [comment]
Thanks for flagging this. It’s been fixed in [this commit](https://github.com/quantumblacklabs/causalnex/commit/372a3901e447ef8eca4492d48f381726aee6136e) and will be available in the next release.

**Comment by oentaryorj** [comment]
Further addressed in [this commit](https://github.com/quantumblacklabs/causalnex/commit/b35f474cf3089cafb8c0a7ed6ace43db3298e2cd) and will be made available in the next release.

Closing this issue now, but feel free to raise a new issue if you find other broken links.
