### ISSUE TITLE
Improve computational efficiency or speed up training process with GPU is applicable

### ISSUE THREAD

**Issue by huanyi89** [quantumblacklabs/causalnex#114]
Hello team,

Thank you for the great package. 
I have some struggle for using this package because of my dataset. The main issue is the speed.
I have data set with at least 50+ features (dimension), and 10K+ observations (rows), which causes a long time for structure learning and Bayesian Network. 

I wonder if there is any opportunity to improve the computational efficiency, and
I wonder since this package uses Pytorch, is that possible to leverage GPU for learning?

If yes, is there any guidance for me to follow?

Thank you

**Comment by oentaryorj** [comment]
This has been implemented in [this commit](https://github.com/quantumblacklabs/causalnex/commit/13aa7473138c4aecb2cd2cc16afba74141d79593) and will be made available in the next release.
