### ISSUE TITLE
NOTEARS with Titanic dataset

### ISSUE THREAD

**Issue by Saladino93** [quantumblacklabs/causalnex#117]
I am playing with the Titanic dataset, using just very few columns to obtain a causal graph using the NOTEARS algorithm as implemented in CausalNex

Here is what I am getting:

<img width="1018" alt="Screenshot 2021-06-02 at 15 10 54" src="https://user-images.githubusercontent.com/23438226/120496306-5ce5e800-c3b5-11eb-9094-4aa5b8d20a3a.png">

This is very strange, how is it possible that Survived implies other factors, such as age?

Is this a problem of my implementation (e.g. did I have to do some data cleaning), a bug, or of the optimisation procedure of the NOTEARS algorithm? 

I am worried, as if I imagine a dataset for which I do not have an expert opinion, or hundreds of features, I might not be able to do completely by hand a causal model.

Thanks.

**Comment by PNEPNE** [comment]
Hi @Saladino93  ,
This graph shows that the strongest conditional dependencies are present between these variables, given this data. 
While, it can give a good starting point quickly, NOTEARS is not a causal algorithm. Causal structure should be validated based on domain knowledge.
Feel free to use parameters like _'W-Threshold'_ , _'beta'_ (in _from_pandas_lasso_) and data preprocessing _(e.g. scaling, discretizing, encoding etc.)_  to get a graph which needs minimum number of changes based on domain knowledge.

**Comment by oentaryorj** [comment]
Closing this for now. Feel free to raise the issue again if playing with the (hyper-)parameters doesn't help.
