### ISSUE TITLE
NOTEARS not scale invariant

### ISSUE THREAD

**Issue by ronnac** [quantumblacklabs/causalnex#118]
## Description
According to this [paper](https://arxiv.org/abs/2104.05441) NOTEARS is not scale invariant, i.e. the causal graph does depend on the measurement units used for the features (centimetres iso. metres, etc)
We have found the same during a try-out.

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
cf. linked paper for details

## Expected Result
The obtained graph should be the same independently of the measurement unit used.

## Actual Result
Obtained graphs are different.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): 0.9.1
* Python version used (`python -V`): Python 3.7.7
* Operating system and version: RHEL 7.7

**Comment by PNEPNE** [comment]
Hi @ronnac ,
The graph generated by NOTEARS shows the strongest conditional dependencies present between variables in the data.
While, it can give a good starting point quickly, NOTEARS is not a causal algorithm. Causal structure should be validated based on domain knowledge.
Feel free to use parameters like _'W-Threshold'_ , _'beta'_ (in _from_pandas_lasso_) and data preprocessing (e.g. scaling, discretizing, encoding etc.) to get a graph which needs minimum number of changes based on domain knowledge.

**Comment by ronnac** [comment]
Thanks, I will try that.
-------- Original message --------From: PNEPNE ***@***.***> Date: 03/08/21  19:22  (GMT+01:00) To: quantumblacklabs/causalnex ***@***.***> Cc: Nick Römer ***@***.***>, Mention ***@***.***> Subject: Re: [quantumblacklabs/causalnex] NOTEARS not scale invariant (#118) 
Hi @ronnac ,
The graph generated by NOTEARS shows the strongest conditional dependencies present between variables in the data.
While, it can give a good starting point quickly, NOTEARS is not a causal algorithm. Causal structure should be validated based on domain knowledge.
Feel free to use parameters like 'W-Threshold' , 'beta' (in from_pandas_lasso) and data preprocessing (e.g. scaling, discretizing, encoding etc.) to get a graph which needs minimum number of changes based on domain knowledge.

**Comment by oentaryorj** [comment]
Answered as above. Thank you @PNEPNE.
