### ISSUE TITLE
Learning with confounders variables

### ISSUE THREAD

**Issue by arita37** [quantumblacklabs/causalnex#12]
## Description

Does the current structure algorithm valid  when there are confounder variables ?
If not, can you add alternative one which take into account.

**Comment by qbphilip** [comment]
Hello and thanks for your question.
The algorithm is valid under the no-unobserved-confounder assumption.

Regarding alternatives, do you have something specific in mind?

Philip

**Comment by benhorsburgh** [comment]
Hey @arita37 thanks for your question. I wanted to follow up from @qbphilip reply and see if you are aware of any other packages / publications / algorithms that offer interesting alternatives? This is definitely something we could explore.

Has this no-unobserved-confounder assumption caused you issues when using CausalNex? If so, are you able to give us any insights into them? Perhaps this could also help us look into potential solutions.

Ben

**Comment by t8ch** [comment]
I guess if you could add unobserved variables (or is this actually possible?), backdoor adjustment might be an option. See e.g. pgmpy or DoWhy.

**Comment by oentaryorj** [comment]
A new feature to add a latent variable and learn its CPD using EM algorithm has been implemented in [this commit](https://github.com/quantumblacklabs/causalnex/commit/6b2dbf316c3ef76368270504ad9464635b92f3c8) and will be made available in the next release. 

Additionally, a [new tutorial](https://causalnex.readthedocs.io/en/latest/03_tutorial/05_latent_variable_tutorial.html) has been created to showcase how to utilise this feature to learn with confounding variables.

Closing this issue for now, but feel free to open a new one if you have any problem/questions regarding the new feature.
