### ISSUE TITLE
Wondering if there's a reference list

### ISSUE THREAD

**Issue by ZhiyinL** [quantumblacklabs/causalnex#120]
Hey, I'm wondering if there's a full list of references anywhere? I‘d love to check out the papers used in Causalnex and, if possible, generally Bayesian Networks for Causal Inference. But I didn't find a place to start. 

Thanks in advance!

**Comment by oentaryorj** [comment]
Hi @ZhiyinL, to my best understanding, the relevant references are as follows:

### Core references
- Original NOTEARS - https://papers.nips.cc/paper/2018/file/e347c51419ffb23ca3fd5050202f9c3d-Paper.pdf
- Dynamic NOTEARS - http://proceedings.mlr.press/v108/pamfil20a/pamfil20a.pdf
- Nonparametric NOTEARS - http://proceedings.mlr.press/v108/zheng20a/zheng20a.pdf

### Other related references
- Generalized scoring functions - https://www.kdd.org/kdd2018/accepted-papers/view/generalized-score-functions-for-causal-discovery
- Lecture notes on probabilistic graphical models - https://ermongroup.github.io/cs228-notes/
- Introduction to Bayesian network - https://infoscience.epfl.ch/record/82584

@qbphilip / @pjbqb, let us know if you have anything else to add?
