### ISSUE TITLE
Running the tutorial No prog neato in path

### ISSUE THREAD

**Issue by JK87iab** [quantumblacklabs/causalnex#122]
## Description
Trying out the first tutorial but getting the error No prog neato in path. 

```
from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE

viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))


ValueError                                Traceback (most recent call last)
~\anaconda3\envs\causelnex\lib\site-packages\pygraphviz\agraph.py in _get_prog(self, prog)
   1320         try:  # user must pick one of the graphviz programs...
-> 1321             runprog = self._which(prog)
   1322         except:

~\anaconda3\envs\causelnex\lib\site-packages\pygraphviz\agraph.py in _which(self, name)
   1568                 return match[0]
-> 1569         raise ValueError("No prog %s in path." % name)
   1570 

ValueError: No prog neato in path.

During handling of the above exception, another exception occurred:
```
## Your Environment
Anaconda mac used brew install pygraphviz
python 3.8
causelnex  0.10.0

**Comment by oentaryorj** [comment]
Thanks @JK87iab. This appears to be a dependency issue with `pygraphviz`. Did you see any error when you installed `pygraphviz`?

**Comment by JK87iab** [comment]
No error while executing pip install pygraphviz

Using pip install "causalnex[plot]" results in the same error

**Comment by oentaryorj** [comment]
I tried to dig the `pygraphviz` codes [here](https://github.com/pygraphviz/pygraphviz/blob/main/pygraphviz/agraph.py), particularly the `_which` function:

```python
def _which(self, name):
   """Searches for name in exec path and returns full path"""
   import glob
   import platform

   if platform.system() == "Windows":
       name += ".exe"

   paths = os.environ["PATH"]
   for path in paths.split(os.pathsep):
       match = glob.glob(os.path.join(path, name))
       if match:
           return match[0]
   raise ValueError(f"No prog {name} in path.")
```

It seems that the neato program cannot be found in the system path. I then looked at the [installation guide](https://github.com/pygraphviz/pygraphviz/blob/main/INSTALL.txt) and, for Mac, the recommended way to install is through homebrew. So perhaps can you try this:
```
brew install graphviz
```
and see if it works?

**Comment by oentaryorj** [comment]
Closing this for now. Do let us know if the problem still persists. Thank you.
