### ISSUE TITLE
Is there a feature that allows exporting the CausalNex generated graphs to DAGitty?  

### ISSUE THREAD

**Issue by ukm5** [quantumblacklabs/causalnex#124]
## Description
The data generated graphs in CausalNex using NOTEARS algorithm is a good place to start working on novel causal inference problems. However, as the problem at hand like in my field of Healthcare gets complicated and subjective, it is often necessary to modify the DAGs using the expertise of clinical experts and doctors. This requires moving the graph from a code-based tool like CausalNex or Networkx to a GUI based tool like DAGitty. A function to export the graph to a format that is DAGitty friendly would allow easier collaboration and moving of graphs between tools. 

## Context
This would facilitate better collaboration across engineers and clinical experts in my field. I am certain this would be a valuable asset to other fields where a data-generated graph is often first step towards developing a Bayesian Network.
 
## Possible Implementation
A function that could be called on the Structured Graph class that output the graph in code format that is in a DAG format and could be copied and pasted in an email or chat and sent to the clinical collaborators. Also, a similar format that could be imported back into CausalNex.

**Comment by oentaryorj** [comment]
Closing this for now. Feel free to re-open the issue should you still find some difficulties.
