### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by vandenheuvel** [quantumblacklabs/causalnex#125]
The FAQ on readthedocs contains a link in [the last section](https://causalnex.readthedocs.io/en/latest/05_resources/05_faq.html#how-can-i-find-out-more-causalnex) to the [RELEASE.md](https://github.com/quantumblacklabs/causalnex/blob/develop/RELEASE.md) file that should have been fixed in 372a3901e447ef8eca4492d48f381726aee6136e but stil seems to link to 

- https://github.com/quantumblacklabs/causalnex/blob/develop/RELEASE, instead of to
- https://github.com/quantumblacklabs/causalnex/blob/develop/RELEASE.md.

So when clicking that link in my browser, I get a 404.

**Comment by oentaryorj** [comment]
Thanks @vandenheuvel for flagging this. The commit has the correct URL, but `.md` is somehow removed when the documentation HTML is rendered. We will try to find a workaround for this issue, which also relates to #113.

**Comment by oentaryorj** [comment]
Further addressed in [this commit](https://github.com/quantumblacklabs/causalnex/commit/b35f474cf3089cafb8c0a7ed6ace43db3298e2cd) and now made available in the [latest documentation](https://causalnex.readthedocs.io/en/latest/05_resources/05_faq.html#where-can-i-learn-more-about-bayesian-networks).

Closing this issue now, but feel free to raise a new issue if you find other broken links.
