### ISSUE TITLE
Instantiating an Inference Engine taking more than an hour. How to reduce time?

### ISSUE THREAD

**Issue by ukm5** [quantumblacklabs/causalnex#128]
I am trying to create an inference engine on structure model containing 27 nodes and 91 edges, on a dataset of size (1277402 × 32). For one is this a computational intensive step? 
The bn.fit_node_states_and_cpds took about 2 minutes but `ie=InferenceEngine(bn)` is taking more than an hour and unfortunately my cluster crashes usually at that time. How do I make this step computationally efficient?
I believe I can use parallel options to query, but I am stuck at instantiating the engine. Any ideas or suggestions?

**Comment by GabrielAzevedoFerreiraQB** [comment]
Hi, Thanks for raising the issue!

A few checks:
- What is the maximum number of categories of your nodes (are they binary, can assume 3 values...)?
- what is the maximum number of parents that a node can have in your structure?
- Is the issue with `ie=InferenceEngine(bn)` or with `ie.query()`?

Thanks!

**Comment by oentaryorj** [comment]
An improved `InferenceEngine` has been implemented in [this commit](https://github.com/quantumblacklabs/causalnex/commit/b89c6d307db2ab35ee7b1d3e805832255b2b3e7d), which no longer calls `query()` at the constructor. This will also be made available in the next release.

Closing this issue for now, but feel free to re-open if you still encounter the issue.
