### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by SophiaLeia** [quantumblacklabs/causalnex#13]
There is an attribute error encountered after running the below statement in the tutorial.

bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")

Pandas version 0.25.1 is used, not version 1.

**Comment by ZainPatelQB** [comment]
Thanks for raising the issue. :)

The `requirements.txt` has `pandas==0.24.0`, how do you have `0.25` installed? I tried reproing with `0.25.1` and whilst I get a bunch of depracation warnings for using `.ix` (as I should), I don't get the error.

Are you absolutely sure that you're using `pandas==0.25.1`? Can you show us the output of `pip list` or `pip freeze`? Pandas got rid of the deprecated `.ix`, but Pandas 0.25.1 definitely has it, so this is super weird.

Can you print a full stacktrace here as well?
