### ISSUE TITLE
Requirement conflict on running `make install-test-requirements`

### ISSUE THREAD

**Issue by hmillerbakewell** [quantumblacklabs/causalnex#133]
## Description
When running `make install-test-requirements` I get the error noted below

## Context
Attempting to perform the appropriate make steps required for CI.

## Steps to Reproduce
1. Create a fresh virtual environment
2. run `make install-test-requirements`

## Expected Result
Installation of all requirements

## Actual Result

```
ERROR: Double requirement given: torch<2.0,>=1.4.0 (from -r test_requirements.txt (line 16)) (already in torch<2.0,>=1.7 (from -r requirements.txt (line 9)), name='torch')
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): 0.11.0
* Python version used (`python -V`): 3.8.10
* Operating system and version: WSL2 / Ubuntu 20.04.2 LTS (Focal Fossa)

## Further Notes

Changing the requirement in test_requirements to `torch >=1.7, <2.0` fixed this for me

**Comment by oentaryorj** [comment]
This has been addressed in a [recent commit](https://github.com/quantumblacklabs/causalnex/commit/ccad9029d739a9244995a0fa5d97a34a21009121) and will be reflected in the next release version.
