### ISSUE TITLE
Error about separate graphs when learning BN

### ISSUE THREAD

**Issue by sersoage** [quantumblacklabs/causalnex#136]
## Description
I am getting the following error "The given structure has 5 separated graph components. Please make sure it has only one."
Structure was learnt with notears  but when i run `bn = BayesianNetwork(sm)` i get the above error. Any advice? How can I select or display the particular subgraphs

## Context
Trying to compute CPT and display markov blanket

**Comment by oentaryorj** [comment]
Thanks for the question.

Ideally, the structure model to be fed into `BayesianNetwork` should be a single connected component with no isolated nodes. 

You can use `plot_structure` to inspect the graph, as per [this tutorial](https://causalnex.readthedocs.io/en/latest/03_tutorial/01_first_tutorial.html). We also have a helper function `sm.get_largest_subgraph()` to extract the largest connected component in the graph

Alternatively, to iterate all subgraphs, you can use the function `weakly_connected_components` in `networkx`. For example:
```
import networkx as nx

for sub_graph in nx.weakly_connected_components(sm):
     print(sub_graph.edges())
```

**Comment by oentaryorj** [comment]
Closing this for now. Feel free to open a new issue if you have another enquiry. Thank you.
