### ISSUE TITLE
Is there a preferred cite source for this repo?

### ISSUE THREAD

**Issue by samialabed** [quantumblacklabs/causalnex#137]
Hi!
Thank you for the awesome work you did with causalnex. I am building a project that uses causalnex and was wondering if you have a preferred citation key or would you prefer I cite the NoTears paper directly?

**Comment by oentaryorj** [comment]
Hi @samialabed, thank you for your feedback :) We are currently working on an option to get the citation from the repository itself, but tentatively the Bibtex entry should look something like this:

```
@misc{Causalnex2021,
author = {Beaumont, Paul and Horsburgh, Ben and Pilgerstorfer, Philip and Droth, Angel and Oentaryo, Richard and Ler, Steven and Nguyen, Hiep and Ferreira, Gabriel Azevedo and Patel, Zain and Leong, Wesley},
month = {9},
title = {{CausalNex}},
url = {https://github.com/quantumblacklabs/causalnex},
year = {2021}
```
@pjbqb or @qbphilip, please let us know if the above entry is fine. Thanks!

**Comment by pjbqb** [comment]
LGTM, thanks @oentaryorj ! And thanks @samialabed for using/citing CausalNex!
