### ISSUE TITLE
FYI: networkx and pandas deprecated features in later libraries

### ISSUE THREAD

**Issue by StephenMSimpson** [quantumblacklabs/causalnex#14]
This is just an "FYI" - not a bug report.

I am using causalnex with Apache RAPIDS with a view to using GPUs for the networkx activity.
There are a couple of version incompatibilities because RAPIDS uses more recent Python libraries than causalnex. These are:

- with networkx 2.4 the weakly_connected_component_subgraphs has been removed (it was announced as deprecated in 2.1; it's now gone).

- with pandas 0.25.0 I get the following attribute error (maybe it's actually a Python 3.7 -> Python 3.6 issue as RAPIDS is using 3.6?):
----> 2 classification_report(bn, test, "G1")

/opt/conda/envs/rapids/lib/python3.6/site-packages/causalnex/evaluation/evaluation.py in classification_report(bn, data, node)
    205     )
    206 
--> 207     return pd.DataFrame.from_dict(report, orient="index")

/opt/conda/envs/rapids/lib/python3.6/site-packages/pandas/core/frame.py in from_dict(cls, data, orient, dtype, columns)
   1172                 # TODO speed up Series case
   1173                 if isinstance(list(data.values())[0], (Series, dict)):
-> 1174                     data = _from_nested_dict(data)
   1175                 else:
   1176                     data, index = list(data.values()), list(data.keys())

/opt/conda/envs/rapids/lib/python3.6/site-packages/pandas/core/frame.py in _from_nested_dict(data)
   8473     new_data = OrderedDict()
   8474     for index, s in data.items():
-> 8475         for col, v in s.items():
   8476             new_data[col] = new_data.get(col, OrderedDict())
   8477             new_data[col][index] = v

AttributeError: 'float' object has no attribute 'items'

**Comment by qbphilip** [comment]
resolved with recent release
