### ISSUE TITLE
AttributeError: module 'pygraphviz' has no attribute 'AGraph'

### ISSUE THREAD

**Issue by mmolet** [quantumblacklabs/causalnex#144]
## Description
I cannot visualize the structure  of the first CausalNex tutorial posted on the website.

## Context
I am trying to learn how to use  the CausalNex library by following the tutorial on the website (step by step).

## Steps to Reproduce

1. Using this code:

import warnings
from causalnex.structure import StructureModel

warnings.filterwarnings("ignore")  # silence warnings

sm = StructureModel()

sm.add_edges_from([
    ('health', 'absences'),
    ('health', 'G1')
])

print(sm)
print(sm.edges)
print(sm.nodes)

from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE

viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)

2. Running the code

## Expected Result
As shown on the CausalNex webstite, a visual of the model should be displayed

## Actual Result
Instead of the visual I get an error.

```
-- If you received an error, place it here.
```
Traceback (most recent call last):
  File "/Users/m/Desktop/test.py", line 22, in <module>
    viz = plot_structure(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/causalnex/plots/plots.py", line 110, in plot_structure
    a_graph = nx.nx_agraph.to_agraph(_sm)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/networkx/drawing/nx_agraph.py", line 137, in to_agraph
    A = pygraphviz.AGraph(name=N.name, strict=strict, directed=directed)
AttributeError: module 'pygraphviz' has no attribute 'AGraph'
```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`):
* Name: causalnex
Version: 0.11.0
Summary: Toolkit for causal reasoning (Bayesian Networks / Inference)
Home-page: https://github.com/quantumblacklabs/causalnex
Author: QuantumBlack Labs
Author-email: causalnex@quantumblack.com
License: Apache Software License (Apache 2.0)
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires: pandas, torch, scikit-learn, pgmpy, pathos, networkx, wrapt, scipy, numpy
* Python version used (`python -V`):
* Python 3.8.8 (v3.8.8:024d8058b0, Feb 19 2021, 08:48:17) 
* Operating system and version:
* Mac Os Big Sur version 11.6

**Comment by EvgeniiaVeselova** [comment]
Hi @mmolet , and thanks for the question!

Since I was unable to reproduce issue with setup
```
networkx             2.8.6
pygraphviz           1.10
causalnex            0.11.0
```
, there are two steps which you can try:

- Re-install `pygraphviz` library following the official installation guide: https://pygraphviz.github.io/documentation/stable/install.html
- Upgrade `causalnex` library, dependencies (such as `networks`) will be upgraded automatically

I hope it helps!
