### ISSUE TITLE
roc_auc gives wrong results

### ISSUE THREAD

**Issue by Byshkin** [quantumblacklabs/causalnex#145]
## Description
Causalnex gives wrong auc

## Steps to Reproduce
roc, auc = roc_auc(..)
Compute probability with bn.predict_probability(..)
from sklearn import metrics
print(auc, metrics.roc_auc_score(..))

**Comment by EvgeniiaVeselova** [comment]
Hi @Byshkin, and thanks for the great question!

The difference between `sklearn.metrics` and `causalnex.evaluation` is that CausalNex calculates micro-averaged ROC-AUC to cover general multi-class prediction and classes imbalance:
```
bn_proba = bn.predict_probability(test, 'G1')
print(bn_proba.shape)
>>> (65, 2)

print(f"Default macro ROC-AUC: {roc_auc_score(ground_truth, bn_proba, average='macro')}")
print(f"Micro ROC-AUC: {roc_auc_score(ground_truth, bn_proba, average='micro')}")
>>> Default macro ROC-AUC: 0.720125786163522
>>> Micro ROC-AUC: 0.8887573964497041

print(f"CausalNex ROC-AUC: {roc_auc(bn, test, 'G1')[1]}")
>>> CausalNex ROC-AUC: 0.8887573964497041
```

We will add comment about micro-averaging to the tutorial. 

I hope it helps!
