### ISSUE TITLE
BayesianNetwork.set_cpd expects MultiIndex columns

### ISSUE THREAD

**Issue by Jack-0-0** [quantumblacklabs/causalnex#146]
## Description
When trying to set the cpd table (using BayesianNetwork.set_cpd) for a node that does not have MultiIndex columns, there is an error: `AttributeError: 'Index' object has no attribute 'levels'`

## Steps to Reproduce
1. Download and unzip 'student-por.csv' from [student.zip](https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip) that is used in the CausalNex first tutorial
2. Run this code:
```
import numpy as np
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from causalnex.structure.notears import from_pandas
from causalnex.network import BayesianNetwork
from causalnex.discretiser import Discretiser
from sklearn.model_selection import train_test_split

data = pd.read_csv("student-por.csv", delimiter=";")[
    ["famrel", "higher", "freetime", "G1", "paid"]
]
struct_data = data.copy()
non_numeric_columns = list(struct_data.select_dtypes(exclude=[np.number]).columns)
le = LabelEncoder()
for col in non_numeric_columns:
    struct_data[col] = le.fit_transform(struct_data[col])
sm = from_pandas(struct_data, w_threshold=0.8)

bn = BayesianNetwork(sm)

discretised_data = data.copy()
data_vals = {col: data[col].unique() for col in data.columns}
discretised_data["G1"] = Discretiser(
    method="fixed", numeric_split_points=[10]
).transform(discretised_data["G1"].values)
G1_map = {0: "Fail", 1: "Pass"}
discretised_data["G1"] = discretised_data["G1"].map(G1_map)

train, test = train_test_split(
    discretised_data, train_size=0.9, test_size=0.1, random_state=7
)
bn = bn.fit_node_states(discretised_data)
bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")

bn.set_cpd(
    "G1", bn.cpds["G1"]
)  # this works as expected

bn.set_cpd(
    "paid", bn.cpds["paid"]
)  # this has an error as it expects multi index columns
```

## Expected Result
The cpd values for node "paid" should be set by `set_cpd`

## Actual Result
There is an error raised: 
`AttributeError: 'Index' object has no attribute 'levels'`
It occurs when trying to run when trying to run bn.cpds["paid"].columns.levels

## Your Environment
* CausalNex version used: 0.11.0
* Python version used: 3.8.12
* Operating system and version: macOS Monterey version: 12.0.1

**Comment by Rishab26** [comment]
Hey @Jack-0-0 This [fix](https://github.com/quantumblacklabs/causalnex/pull/151) should help.

**Comment by oentaryorj** [comment]
Thanks for reporting the issue. We have merged this [PR](https://github.com/quantumblacklabs/causalnex/pull/151), with additional test case(s). Hope this is fine now.
