### ISSUE TITLE
Remaining use of load_boston dataset in docs

### ISSUE THREAD

**Issue by koaning** [quantumblacklabs/causalnex#147]
I wanted to re-open https://github.com/quantumblacklabs/causalnex/issues/91 but didn't have the permissions, hence the new issue. Aren't you folks using the same boston dataset [in another part of the docs](https://causalnex.readthedocs.io/en/latest/03_tutorial/02_dist_schema_tutorial.html)?

**Comment by qbphilip** [comment]
Hello Vincent,
As already mentioned in #91, we do so without the problematic `B` column. We currently plan to replace the notebook when we upgrade to the sklearn version that deprecates the dataset as we are low on developer capacity. 
I renamed the title for clarity.

As always, we appreciate code contributions. Note that neither the breast cancer nor California housing (as suggested by sklearn as replacement) are appropriate for this doc as they only contain continuous features although being a regression and of similar dimensions.
