### ISSUE TITLE
Evaluating "Causal Discovery from Incomplete Data: A Deep Learning Approach"

### ISSUE THREAD

**Issue by manmeet3591** [quantumblacklabs/causalnex#154]
## Context
I face a lot of problems in real-world Earth science datasets which have a lot of missing data

## Possible Implementation
https://arxiv.org/pdf/2001.05343.pdf
Please evaluate the implementation of this paper. Thank you.

**Comment by rnrahman** [comment]
Hi, thank you for the suggestion. This is certainly an interesting approach for us to evaluate, but at this point our priority is to implement more established algorithms that tally with our roadmap (deep learning-based methods are beyond our scope at this stage). If you have other suggestions, happy to hear! Contributions welcome as well.
