### ISSUE TITLE
InferenceEngine on infinite loop after creating latent variable

### ISSUE THREAD

**Issue by achuinar** [quantumblacklabs/causalnex#164]
## Description
I am  working on the creation of a model to predict fire occurrences. 

I generated this graph: 

![image](https://user-images.githubusercontent.com/26856205/179129884-37d1f72a-4d96-4c45-a770-061e3f59ed67.png)

and extracted the CPDs from it. Then initiating the InferenceEngine works fine.

Then, I tried to introduce a latent variable, run the latent CPDs calculation and re-create the InferenceEngine but it keeps running forever which makes me suspect an infinite loop like what was previously reported in a similar ticket. 

## Context
I wanted to perform a 

## Steps to Reproduce
1.  Add node to network 
```
bn.add_node(
    node="high_number_of_people_prone_to_inattention",
    edges_to_add=[
        ("high_number_of_people_with_not_enough_sleep", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_single_parents", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_people_with_disabilities", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_elderly_people_75plus", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_people_prone_to_inattention", "fire_density")
    ],
    edges_to_remove=[],
) 
```
2. Set boundaries 
```
from causalnex.estimator.em import EMSingleLatentVariable

boundaries_inat = EMSingleLatentVariable.get_default_box(
    sm=bn.structure,
    node_states={
        **bn.node_states,
        'high_number_of_people_prone_to_inattention': {0, 1}
    },
    lv_name='high_number_of_people_prone_to_inattention'
)

boundaries_inat['fire_density'][1].loc[1 ,0] = .8 
```
3. Fit latent CPDs 
```
bn = bn.fit_latent_cpds(
    lv_name="high_number_of_people_prone_to_inattention",
    lv_states=[0, 1],
    data=full_training_sample,
    box_constraints=boundaries_inat,
    n_runs=30,)
```
4. Try to generate InferenceEngine
```
from causalnex.inference import InferenceEngine
ie = InferenceEngine(bn)
```

## Expected Result
Should generate InferenceEngine object

## Actual Result
Runs forever

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): Version: 0.11.0
* Python version used (`python -V`): 3.8.7
* Operating system and version: Mac OS Big Sur 11.6.7

**Comment by RyanNgQB** [comment]
Hi @achuinar, thanks for raising this ticket.

Issue seems to be arising due to addition of nodes that are not in the existing BN subgraph while also adding in the latent variable. Hence it is getting stuck in a while loop as you've suspected.

In your case specifically, `high_number_of_people_with_not_enough_sleep` and `high_number_of_single_parents` were not captured in the largest subgraph and should first be added before attempting to add the latent variable.

Could you try this as a temporary workaround while a more permanent solution is explored?

Before step 1. in your steps to reproduce:

```
# Manually add additional nodes to the subgraph first
bn.add_node(
    node="high_number_of_people_with_not_enough_sleep",
    edges_to_add=[("high_number_of_people_with_not_enough_sleep", "fire_density")],
    edges_to_remove=[],
)

bn.add_node(
    node="high_number_of_single_parents",
    edges_to_add=[("high_number_of_single_parents", "fire_density")],
    edges_to_remove=[],
)

# Fit node states and CPDs without latent variable "fire_density" but with additional nodes
bn.fit_node_states_and_cpds(full_training_sample.drop(["fire_density"], axis=1))
```
Then modify step 1. to:
```
bn.add_node(
    node="high_number_of_people_prone_to_inattention",
    edges_to_add=[
        ("high_number_of_people_with_not_enough_sleep", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_single_parents", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_people_with_disabilities", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_elderly_people_75plus", "high_number_of_people_prone_to_inattention"),
        ("high_number_of_people_prone_to_inattention", "fire_density")
    ],
    edges_to_remove=[
        ("high_number_of_single_parents", "fire_density"),
        ("high_number_of_people_with_not_enough_sleep", "fire_density")
    ],
) 
```
This should prevent getting stuck in the infinite loop by splitting up the steps of adding nodes to the subgraph and adding the latent variable.
