### ISSUE TITLE
Relationship between do intervention versus uplifting models based with  causal graph aware estimand

### ISSUE THREAD

**Issue by tonyabracadabra** [quantumblacklabs/causalnex#166]
I've been browsing through the codebases of several popular causal inference libraries and I am especially interested in the relationship of `do-intervension` vs uplifting models (methods in econml/causalml).

So here is my understanding:
It feels like `do-intervention` does a pretty similar thing as compared to `doWhy`'s identify-estimate step, where the estimation of an action is evaluated on an estimand retrieved from a causal graph with do calculus, but the only difference is causalnex is using bayesian network for inference instead of models commonly used in CATE.

Am I thinking it in a correct way or did I miss anything? If they are different, what are their particular use cases and what are the caveats I should be aware of when choosing these methods?

**Comment by GabrielAzevedoFerreiraQB** [comment]
Hi @tonyabracadabra,

I think you are spot on. 

Both approaches try to find the effect of interventions as opposed to simply observations in the data. For Causalnex, we start with a BN that supposedly encodes causality and choose the variable(s) to intervene on. An "intervention" on these variables means setting the variables a given value and removing all parents of such variables - this is effectively removing all cofounder effects and is know as "mutilating" the graph. 

I can't deep dive into doWhy, but causalml's idea of intervention typically involve training 2 separate models (with and without treatment) and comparing the difference. In BNs, on the other hand, we find the reasons for cofounding effects correcting for them by changing the network.

I hope it helps, and thanks for all the contributions :)
