### ISSUE TITLE
the same process different results

### ISSUE THREAD

**Issue by he-weisong** [quantumblacklabs/causalnex#178]
Run the latest version of causalnex with the same two pieces of code before and after the intervention but with different results

**Comment by ElisabethSesterHussQB** [comment]
Hello thank you for reaching out!
Interventions can be made using the `do_intervention` method provided in the `InferenceEngine` class. They can be reversed by using the `reset_intervention` method. This will give you the original distribution before the intervention was made. An example can be found in the last `Do Calculus` section of [this notebook](https://github.com/quantumblacklabs/causalnex/blob/develop/docs/source/03_tutorial/01_first_tutorial.ipynb).
We hope this helps! If not, please feel free to reach out again. You are more than welcome to share specific code snippets. This will help us understand your issue even better.
