### ISSUE TITLE
Possibility to manually define the CPTs

### ISSUE THREAD

**Issue by helderc** [quantumblacklabs/causalnex#18]
Hello, is there an way to define manually the CPTs (Conditional Probability Tables)? I couldn't find anything related to this in the documentation.

If there isnt, would be interesting to have this feature.
Thank you all for the great library.

**Comment by benhorsburgh** [comment]
Hey @helderc. At present, there isn't a way to manually define them.

I agree it would be interesting to have this feature, and I think it would be relatively easy to add. We're currently looking into a possible implementation.

Out of curiosity, what sort of things would you use this to explore? This may help inform an implementation.

**Comment by helderc** [comment]
Hi @benhorsburgh.
I would like to use this feature mostly as a didactic way to implement a Bayes net and do some inference.
So basically, would be to perform calculations based on made-up examples.

Thank you all.

**Comment by mehtabpathan** [comment]
Hi @helderc 

It is possible to update the CPT after some serious pandas gymnastics - have a look at such function below. Essentially you will have to recreate a multi-index dataframe of the same format as the BN.cpds[_node_you_want_to_change_]

@benhorsburgh - An implementation of to update CPTs of name nature as pomegranate library would be welcome! - https://pomegranate.readthedocs.io/en/latest/Distributions.html  

```
def _set_CPDS(bn):
    '''
    Updates and returns the bayesian network with updated CPDs
    :param bn:
    :return:
    '''
    # Overwrite BN CPDS with those saved
    for node, cpd in bn.cpds.items():
        df = pd.read_csv(f"./data/output/CPDS/{node}.csv")
        # For DataFrames only containing priors (node_name, value)
        if len(df.columns) == 2:
            df = df.set_index(node)
            df.columns = ['']
        else:
            df = df.pivot_table(index=node, columns=[i for i in df.columns if i not in [node, 'value']], values='value')
            if len(df.columns.names) == 1:
                df.columns = pd.MultiIndex(levels=[df.columns.values], codes=[range(3)], names=[df.columns.names])
        # Update the CPDS with those specified
        bn.cpds[node].update(df)
    return bn
```

**Comment by oentaryorj** [comment]
A new function `set_cpd` has been implemented in [this commit](https://github.com/quantumblacklabs/causalnex/commit/6031e1a6978c083515f8ddbc0a11e05e91c0a115) and will be made available in the next release.
