### ISSUE TITLE
Installation instruction does not contain set up with Docker

### ISSUE THREAD

**Issue by iamkuldeepsingh** [quantumblacklabs/causalnex#19]
## Description
Most of the developers are using python with Docker now a days and I see instructions contain only conda and pycharm. I will suggest to have the setup with Docker as well

## Context
I still find it difficult to setup casualnex on local setup, however when I did with Docker it was much simpler and reproducible, hence would like to add this feature and if needed I can do that and contribute as well

## Possible Implementation
We could use a base python image or a standard image loaded with other packages and extend it (if needed I can share how I did it)

## Possible Alternatives
Alternatives are already available

**Comment by DanielF29** [comment]
@iamkuldeepsingh 
Could you share the docker image for CausalNex?? or the steps of how you did it?

**Comment by oentaryorj** [comment]
Addressed in this [commit](https://github.com/quantumblacklabs/causalnex/pull/163)

**Comment by oentaryorj** [comment]
Addressed in this [PR](https://github.com/quantumblacklabs/causalnex/pull/163).
