### ISSUE TITLE
Add GitHub Actions installation jobs across environments

### ISSUE THREAD

**Issue by Eve-ning** [quantumblacklabs/causalnex#190]
## Description
As discovered by many during a recent hackathon workshop in SG, we found that many users, (mostly Windows & Mac) faced problems installing through pip / conda. 

Furthermore, due to a recent update in `pygraphviz`, it broke tutorials at that time.

## Context
I do find this library's direction good, however, could use more stability, especially when workshops are conducted with it.

## Possible Implementation
GitHub Actions (Free) can run pip install / conda install pipelines on many environments.
See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

The workflow may be something like this:

| Envs                | Windows | Mac    | Ubuntu |
|---------------------|---------|--------|--------|
| Installation Method |         |        |        |
| pip                 | Job 1   | Job 2  | ...    |
| pip w/ pygraphviz   |         |        |        |
| conda               |         |        |        |
| conda w/ pygraphviz |         |        | Job n  |

Note that dimensionality can be reduced through matrices. Which takes a cartesian product of lists provided.
See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by zzzzzzzzzzzzz** [comment]
Hello,

Apologize for a long response. We recently moved to pyviz library to allow fancier visualizations and get rid of pygraphviz which caused this issue.

Also, we have .circleci pipelines to ensure the package works on different platforms.
