### ISSUE TITLE
Unsuitability of Notears for causal inference 

### ISSUE THREAD

**Issue by arainboldt** [quantumblacklabs/causalnex#195]
Causalnex fills an important gap in the python ecosystem. Thank you all for your work on the package and for keeping it OS.

## Description
Given this paper: https://arxiv.org/abs/2104.05441v2

And this paper: https://proceedings.neurips.cc/paper/2021/file/e987eff4a7c7b7e580d659feb6f60c1a-Paper.pdf

It seems odd that no other structure learning methods have been incorporated into the package.

## Context
There are a lot of structure learning methods that are specifically designed with causal inference in mind. it's worth exploring how these methods can be implemented in the causalnex framework.

**Comment by ElisabethSesterHussQB** [comment]
Thank you for raising this issue! 
We are aware of the limitations of NOTEARS and the existence of other structure learning algorithms that might be more suited depending on the situation.
Therefore, we have implemented two new algorithms that will be part of the next release:

- **DAGGNN**: A Deep learning approach to train an autoencoder which is parametrised by a graph neural network - based on [this paper](https://par.nsf.gov/servlets/purl/10100175)
- **NOFEARS**: Extend NOTEARS by implementing a Karush-Kuhn-Tucker (KKT)-search algorithm on top of the current implementation as proposed in [this paper](https://proceedings.neurips.cc/paper/2020/file/28a7602724ba16600d5ccc644c19bf18-Paper.pdf)

With this release, we hope to give our users more options and we will keep our eyes open for more ways to enhance `causalnex` in the future. Please do keep making suggestions that we can look into!

**Comment by arainboldt** [comment]
@ElisabethSesterHussQB thanks for the very thorough reply and the references! I've very curious to read through them. The repo is really useful and fun, and I look forward to seeing it grow. Happy to know that you'll be expanding available algos for structure learning. Cheers!

**Comment by GabrielAzevedoFerreiraQB** [comment]
Thanks a lot for support, @arainboldt !
