### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by tatianamck** [quantumblacklabs/causalnex#20]
## Description
I found a typo on the tutorial (https://causalnex.readthedocs.io/en/latest/03_tutorial/03_tutorial.html):
![image](https://user-images.githubusercontent.com/53178461/75887137-15665a00-5e08-11ea-8dc8-975d43088e57.png)

It should be 'us' instead of 'as'.

**Comment by SteveLerQB** [comment]
> ## Description
> I found a typo on the tutorial (https://causalnex.readthedocs.io/en/latest/03_tutorial/03_tutorial.html):
> ![image](https://user-images.githubusercontent.com/53178461/75887137-15665a00-5e08-11ea-8dc8-975d43088e57.png)
> 
> It should be 'us' instead of 'as'.

Dear @tatianamck, thanks for spotting this. Will fix this internally :)

**Comment by mzjp2** [comment]
Thanks so much for bringing this up @tatianamck, it's been solved by this commit https://github.com/quantumblacklabs/causalnex/commit/8092e6aaada8ce11deefd4d80ddef70acc48dfcf and should be released shortly :)
