### ISSUE TITLE
Find out the number of cycles

### ISSUE THREAD

**Issue by geet-8** [quantumblacklabs/causalnex#206]
## Description
After plotting the graph, it would be great if we can have the number of cycles that the plot has after plotting 
## Context
It would be important to know the various cycles in the causal graph and also it would be appropriate to know what node is being caused by what other node 
**sm = from_pandas(struct_data)
cycles = sm.find_cycles()
for cycle in cycles:
  print(cycle)**

**Comment by GabrielAzevedoFerreiraQB** [comment]
Thanks a lot for the feature request, @geet-8 

The CausalNex graph is what we call a DAG - Direct Acyclic Graph, which means it  should have no cycles by definition. 

If the the `from_pandas` function doesn't converge before the max iterations is hit OR the user doesnt set a w_threshold, then cycles may appear - and we do throw warnings in that case.

Thank you!
