### ISSUE TITLE
Negative probabilities (linear model in BN?)

### ISSUE THREAD

**Issue by t8ch** [quantumblacklabs/causalnex#22]
First, thanks for the grate package!

Using the InferenceEngine I can "do" and obtain negative probabilities. 
I was trying something like this from the example in the tutorial:
`ie.do_intervention("higher",
                   {'yes': x,
                    'no': 1-x})`
`print("updated marginal G1", ie.query()["G1"])` 
Here, I can set values for `x` outside the range of [0,1], which I think is not ideal.

A more relevant question occurred to me from observing that the output of `ie.query()["G1"]` after the intervention is a perfectly linear function of `x`, extending into the negative. Are the CPDs in your model linear functions by design? Shouldn't these functions be bounded?

**Comment by pjbqb** [comment]
At the minute it's a bit of a "garbage in, garbage out" situation. Good point thought that a check could be implemented to make sure that the input is a genuine probability - please do feel free to implement this if you would like :) .

I'm a bit confused by your second point. The CPDs/updated under intervention and the Junction Tree Algorithm will not normally be a linear update (though might be in some cases depending on the structure of the graph). The updates follow the JTA.

**Comment by t8ch** [comment]
Thanks for your quick reply!
That's indeed something I could try do implement rather quickly. [However, I am bit surprised that there is an algorithm for PDFs downstream that does not mind negative prob (!?)]

As for my second point, I wasn't aware of the JTA. And I have to admit I am not familiar with it. Could you comment on how the JTA incorporates interventions, e.g. is it using backdoor adjustment? More generally, could you refer to some resources for the connection of JTA and do-operations? Thanks.

**Comment by pjbqb** [comment]
The JTA itself doesn't handle interventions per se; it's only responsible for propagating information. To perform interventions/do-operations, we "mutilate" the graph to break parental relationships on any node we're intervening on and then any other evidence that's given then uses the JTA on this mutilated graph.

We don't have any metrics implemented to actually do the measuring of the effect of confounders (like backdoor adjustment)

**Comment by t8ch** [comment]
Thanks for elaborating on that!
I think having a "proper" variable adjustment would be a great feature, adding even more value to the package.

Btw, I also added a pull request for restricting the probabilities to [0,1].
