### ISSUE TITLE
Questions about SCMs

### ISSUE THREAD

**Issue by ranared** [quantumblacklabs/causalnex#23]
1. Do you think it is proper to use CausalNex with time series data? (~55 years of annual records, pct change applied). I know on the website, it says it is recommended to use CausalNex with at least 1000 instances but I keep the number of nodes as 5 or 6, so I think maybe it can work. But I'm not really sure about that.

2. What are the edge weights representing? How important are their quantities? And what should we understand if they are positive or negative?

3. How should we decide on the threshold?

I would be really glad if you can help. Thanks.

**Comment by pjbqb** [comment]
Hey, 
On 1.  BNs are inherently atemporal apart from perhaps our "assumption" that parent happens before child node. Dynamic Bayesian Networks respect time (and there's a great paper on structure learning for DBNs here: https://arxiv.org/abs/2002.00498 ;) ). We hope to eventually integrate DBNs into CausalNex.

2. The edge weights from the structure learning are outputs from NOTEARs algorithm: https://arxiv.org/abs/1803.01422 . Their absolute value represents the strength of the conditional dependence between nodes as determined by the algorithm.

3. Experimentation! Depending on a) the strength of the relationship between nodes within the data (i.e. highly related, loosely related, mainly spurious), will determine how strict you need to set your threshold; there is no "hard" rule. My best advice is to run the algorithm, inspect the weight outputs and then decide on an appropriate threshold for your case/data.

**Comment by ranaozcan** [comment]
Thanks for the detailed answer! :) 
Just to make sure, the sign of an edge weight doesn't mean anything, we just need to look at the absolute value, right?

**Comment by SteveLerQB** [comment]
@ranaozcan Hi Rana, negative edge weight means negative causal relationship between two variables. 

For example, if A -> B, and the edge weight is negative, it means B tends to decrease when A increases in value. Hope this answers your question! :)

**Comment by oentaryorj** [comment]
Already addressed as above
