### ISSUE TITLE
pygraphviz is not listed in the requirements

### ISSUE THREAD

**Issue by ogencoglu** [quantumblacklabs/causalnex#26]
Since the latest update `plot_structure` requires _pygraphviz_ requirement which is missing from the _requirements.txt_.

**Comment by mzjp2** [comment]
Hey @ogencoglu, I believe that `pygraphviz` is an optional dependency under `extras_require`, so you can install it with `pip install “causalnex[plot]"`:

https://github.com/quantumblacklabs/causalnex/blob/f053bee25108a3e62c5ade6e0e7f5b142d1652b6/setup.py#L57-L60

Does that clear it up? My understanding is that not everybody wants to use the plotting capability and `pygraphviz` is a bit of a heavy/complex dependency, so making it optional makes sense.

Perhaps we can document this better, though!
