### ISSUE TITLE
API docs is not up-to-date

### ISSUE THREAD

**Issue by ogencoglu** [quantumblacklabs/causalnex#28]
For example:

https://causalnex.readthedocs.io/en/latest/source/api_docs/causalnex.plots.plot_structure.html#causalnex.plots.plot_structure

vs.

https://github.com/quantumblacklabs/causalnex/blob/master/causalnex/plots/plots.py

**Comment by SteveLerQB** [comment]
Hi dear @ogencoglu,

Thanks for raising this. I have just updated the documentation to its latest version, so the documentation should be showing the latest version of the tutorial. 

Please clear your browser cache data and refresh the tutorial webpage to show the latest version. And do let me know if you still have any problems. 🙂

**Comment by ogencoglu** [comment]
Thank you very much!
