### ISSUE TITLE
classification_report

### ISSUE THREAD

**Issue by ri3017** [quantumblacklabs/causalnex#36]
## Description
Hi! I have one problem with classification_report method. It throws an AttributeError: 'float' object has no attribute 'items'. The roc_auc method is working properly called with the same parameters as in the case of classification_report

## Actual Result
File "C:\Users\......\anaconda3\lib\site-packages\causalnex\evaluation\evaluation.py", line 207, in classification_report
    return pd.DataFrame.from_dict(report, orient="index")
  File "C:\Users\......\anaconda3\lib\site-packages\pandas\core\frame.py", line 1179, in from_dict
    data = _from_nested_dict(data)
  File "C:\Users\......\anaconda3\lib\site-packages\pandas\core\frame.py", line 8486, in _from_nested_dict
    for col, v in s.items():
AttributeError: 'float' object has no attribute 'items'

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): 0.5.0
* Python version used (`python -V`): 3.7
* Operating system and version: windows 10

**Comment by SteveLerQB** [comment]
hi @ri3017,

Have you solved your problem? I believe it is your pandas package version problem. Can you print out the pandas version you are using by executing `pip show pandas`?
