### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by weiji14** [quantumblacklabs/causalnex#38]
Hi there,

Just wondering if there's any plans for `causalnex` to support Python 3.8? I've had a look at the dependencies in the [`requirements.txt`](https://github.com/quantumblacklabs/causalnex/blob/f053bee25108a3e62c5ade6e0e7f5b142d1652b6/requirements.txt#L1-L8) file and they all seem to support Python 3.8 on PyPI.

Thanks, and great documentation by the way!

**Comment by qbphilip** [comment]
FYI we are working on this right now (general bump of versions, also pandas >=1.0, latest networkx etc)

**Comment by qbphilip** [comment]
Python 3.8 is now supported
