### ISSUE TITLE
[minor issue] `make lint` fails to install `black` if already not installed

### ISSUE THREAD

**Issue by GabrielAzevedoFerreiraQB** [quantumblacklabs/causalnex#39]
## Description
`Make lint` fails if black is not installed. It fails with the message `premission denied`

This is not a huge issue (we can install it on our own), but I believe the expected behaviour is for `Make lint` to install `black` if Python >=3.6 and 

## Context
cloning the repo and contributing.

## Steps to Reproduce

I tested initialising environments with the versions of python 3.5, 3.6 and 3.7, installing the requirements and then running `make lint`

3.5: all passed
3.6 and 3.7: the following error message

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/test_37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/test_37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gabriel_azevedo_ferreira/Documents/Projects/CAUSALNEX_RND/causalnex/tools/min_version.py", line 46, in <module>
    subprocess.run(run_cmd, check=True)
  File "/opt/anaconda3/envs/test_37/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/anaconda3/envs/test_37/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/envs/test_37/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'black'
```

The images are as follows
<img width="1047" alt="Screenshot 2020-04-25 at 10 41 11 AM" src="https://user-images.githubusercontent.com/57528979/80269619-e96aa500-86e3-11ea-9875-02bccad36105.png">

<img width="1032" alt="Screenshot 2020-04-25 at 10 33 37 AM" src="https://user-images.githubusercontent.com/57528979/80269616-e53e8780-86e3-11ea-9c9a-e765333feab7.png">

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Python version used (`python -V`):
* Operating system and version: Mac OS catalina

**Comment by mzjp2** [comment]
Should be fixed in the release where we drop 3.5 support and add 3.8 support - the problem came from the `min_version` script we were using I believe. Feel free to re-open if still an issue.
