### ISSUE TITLE
Parameter learning with continuous data

### ISSUE THREAD

**Issue by aynsleybernard** [quantumblacklabs/causalnex#44]
## Description
Using the discrete parameter learning functionality on a standard BN structure (20-30 nodes and an intuitive discretisation for each) requires huge amounts of memory. Parameter learning is faster and more memory-efficient when calculated implementing parameter learning on continuous data in other packages (Gaussian BN). 

## Context
When suitable normality assumptions are being met Gaussian BNs perform well, they don't require any loss of information through discretisation and the memory requirements of parameter learning are severely reduced. I've also seen in your docs that this is already on your roadmap to have this implemented - an ETA would be awesome!

**Comment by qbphilip** [comment]
Hello, 
I am afraid, I don't have an update on the ETA for the functionality. We are happy for any code contributions!

Besides the computational load, its a tradeoff between discretisation- and model-misspecification error?
