### ISSUE TITLE
do_intervention never ends running despite simple query

### ISSUE THREAD

**Issue by ironcrypto** [quantumblacklabs/causalnex#45]
Hi QB––
## Description
I am running a do-calculus on a small dataset (116x32) with 2 to 4 discretized buckets.
The BN fits the CPDs in 2 sec, so relatively good perf.

However a simple do-intervention takes forever and even never ends running, I waited several hours then I interrupted kernel.

## Steps to Reproduce

$ from causalnex.inference import InferenceEngine
$ ie = InferenceEngine(bn)
$ ie.do_intervention("cD_TropCycl", {1: 0.2, 2: 0.8})
$ print("distribution after do", ie.query()["cD_TropCycl"])

## Expected Result
Shouldn't it be running just a few seconds given the low number of buckets?
How long does it normally take? 

## Actual Result
no results returned after hours running a simple query.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): 0.5.0
* Python version used (`python -V`): python 3.7.6
* Operating system and version: osx 10.15.14 on 2.3 GHz Quad-Core Intel Core i5

Thank you very much!!

**Comment by ironcrypto** [comment]
Hello @qbphilip 
Any chance I get get an answer or help on this?
Thank you

**Comment by mingli2607** [comment]
Same problem when I do intervention on a little large dataset. Some nodes can be queried easily while  some cannot be.

**Comment by qbphilip** [comment]
@ironcrypto Could you replicate this on a minimum example, e.g. on a small synthetic dataset?

**Comment by ironcrypto** [comment]
@qbphilip yes I think so. Do you have such dataset or should I create it?

**Comment by SteveLerQB** [comment]
Hi @ironcrypto, it would be great if you could provide us this dataset to debug this. Thanks :)

**Comment by ironcrypto** [comment]
Sure. here attached the Notebook and the dataset to reproduce. 
You will see that I interrupted the last two instructions of Do-Calculus as an effect of very high latency. 
I would be curious to see if you get the same problem or if error is on my side. Maybe a bad discretization policy? I doubt because it is pretty simple though.

[github_qb_bug_45.zip](https://github.com/quantumblacklabs/causalnex/files/4831927/github_qb_bug_45.zip)

**Comment by ironcrypto** [comment]
Hi,
Have you been avale to reproduce the bug or do you observe the same latency?
Thank you

**Comment by FrancescaSogaroQB** [comment]
thank you @ironcrypto for reporting this. This is also linked to issue #100. The above has been fixed with this [commit](https://github.com/quantumblacklabs/causalnex/commit/9de529cbac7727c798d4a4aaa811ed453ad2d783) will be available in the next CausalNex release.
