### ISSUE TITLE
Plotting the DAGs without pygraphviz

### ISSUE THREAD

**Issue by sina-salek** [quantumblacklabs/causalnex#48]
Hi, Thank you for the package, it makes lots of causal inference jobs much easier. And the tutorial helps with getting started quickly. 

I was just wondering if there is any way of plotting the DAGs inside causalnex without pygraphviz. It's bit of pain to get that running on Windows.

Thanks

**Comment by qbphilip** [comment]
Hello, `networkx` has drawing functionality using `matplotlib`, which we used in fact before the current pygraph implementation: https://networkx.github.io/documentation/stable/reference/drawing.html

Quick example:
```
sm = StructureModel()
sm.add_edges_from([(0, 1), (1, 2), (3, 2)])

fig, ax = plt.subplots()
nx.draw_circular(sm, ax=ax)
fig.show()
```

Philip

**Comment by sina-salek** [comment]
Thanks, this is very helpful.
