### ISSUE TITLE
how to fit_cpds on batch?

### ISSUE THREAD

**Issue by ziyuwzf** [quantumblacklabs/causalnex#52]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by oentaryorj** [comment]
Closing this issue for now as there is insufficient description and/or example on how the batched fit should be done. Feel free to raise a new issue should this feature be needed
