### ISSUE TITLE
Do-Calculus using CausalNex

### ISSUE THREAD

**Issue by PJPC2020** [quantumblacklabs/causalnex#66]
## Description
How to assess the effect of an intervention? How to compute see and do probabilities?

## Context
I want to perform Level 2 of Causal Inference - Do-Calculus. 

## Process
Considering the student performance example on the CausalNex website. 

<img width="816" alt="image" src="https://user-images.githubusercontent.com/69321074/91465161-4e750980-e842-11ea-8789-6d518d260cd8.png">

I am using the "higher" node as the intervention and performing do_intervention on it. I get a probability distribution for G1 based on the intervention. When I try to compare the probability distribution of G1 before the intervention, it is the same. 

pred = ie.query({"higher": "yes"}), gives
'higher': {'no': 0.0, 'yes': 1.0}
'G1': {'Fail': 0.206829529425519, 'Pass': 0.793170470574481}

ie.do_intervention("higher",{"yes":1.0,"no":0.0})
ie.query()
'higher': {'no': 0.0, 'yes': 0.9999999999999998}
'G1': {'Fail': 0.20682952942551894, 'Pass': 0.7931704705744809}

I want to understand how do_intervention differs? How do I compute the see probabilities (before intervention) and do probabilities?

**Comment by oentaryorj** [comment]
Hi @PJPC2020, you can learn more about the difference from articles such as [this](http://web.mit.edu/tger/www/papers/Observing%20and%20Intervening%20(Meder,%20Gerstenberg,%20Hagmayer,%20Waldmann,%202010).pdf). 

More details on how the probabilities are computed can be found at https://github.com/quantumblacklabs/causalnex/blob/develop/causalnex/inference/inference.py

**Comment by bgeils** [comment]
facing this same issue - below is a good example to test

```
print('G1 | observe they want to pursue higher education:', ie.query({"higher": "yes"})['G1'])

ie.do_intervention("higher", {'yes': 1.0, 'no': 0.0})
print('G1 | do(pursue higher education)', ie.query()["G1"]) 
```
