### ISSUE TITLE
Obtaining conditional probability distribution of the whole graph after a do-intervention

### ISSUE THREAD

**Issue by himanshi4693** [quantumblacklabs/causalnex#67]
## Description
I'm trying to obtain an interventional data distribution, i.e., I want to intervene on a specific node and see how that affects the conditional probabilities in the entire graph. Currently, it's possible to intervene on a specific node and query the **marginals** of every other node. Let's say I have a graph with 3 nodes (A, B, C), one of them (A) is confounding the causal relation between the other two (B --> C). I can intervene on the confounding node A, and I want to obtain the probabilities P(B | A) and P(C | B, A). I suppose the former is directly inferred from the marginal P(B) (since we know the interventional value of A). But how can I obtain P(C | B, A)?

## Context
Database repair problems, where you'd want to remove unwanted causal effects from the distribution

## Possible Implementation
Possibility to query conditionals along with marginals, or to sample from the distributions resulting from an intervention?

**Comment by oentaryorj** [comment]
I guess this can be done by examining the `cpds` attribute after the do-intervention. A rough sketch is given below:
```python
import pandas as pd

from causalnex.structure import StructureModel
from causalnex.network import BayesianNetwork
from causalnex.inference import InferenceEngin

sm = StructureModel()
sm.add_edges([('A', 'B'), ('B', 'C'), ('A', 'C')])

data = pd.read_csv(...)
bn = BayesianNetwork(sm)
bn.fit_node_states_and_cpds(data)
bn.do_intervention({'A': {...})

print(bn.cpds['B'])  # this should give P(B | A)
print(bn.cpds['C'])  # this should give P(C | B, A)   
```

Hope this helps.

**Comment by oentaryorj** [comment]
Closing this issue for now. Feel free to re-open or raise a new issue when you have further enquiry.
