### ISSUE TITLE
Understanding DAGRegressor behaviour 

### ISSUE THREAD

**Issue by nick-gorman** [quantumblacklabs/causalnex#76]
Hey!

I was wondering if someone could help me understand the behaviour of this simple DAGRegressor. I'm getting a similar issue in a more complex example.

In the simple example I just use the regressor to fit  the nonlinear relationship y = x ^ 2. When I then plot the result of feeding the training data back into the predict method we can see that it works ok. 

![image](https://user-images.githubusercontent.com/40549624/100840030-60adb600-34c9-11eb-914c-f0bb69cb9633.png)

However, when I feed it a much smaller set of data to predict with I get very different results, and changing the first x value to predict for changes the prediction for the second x value. 

```
print(reg.predict(pd.DataFrame({'x': [0.0, 10.0]})))
# [2634.15699576 4040.53486056]

print(reg.predict(pd.DataFrame({'x': [1.0, 10.0]})))
# [2696.09601899 3978.59717296]
```

I would have thought each x value would have produced a prediction independent of any other x values. See the example code below.

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from causalnex.structure.pytorch import DAGRegressor

x = np.linspace(0.0, 100, 500)
y = x ** 2

reg = DAGRegressor(threshold=0.0,
                   alpha=0.0,
                   beta=0.5,
                   fit_intercept=True,
                   hidden_layer_units=[10, 10],
                   standardize=True
                   )

X = pd.DataFrame({'x': x})
y = pd.Series(y, name="MEDV")

reg.fit(X, y)

print(reg.predict(pd.DataFrame({'x': [0.0, 10.0]})))
# [2634.15699576 4040.53486056]

print(reg.predict(pd.DataFrame({'x': [1.0, 10.0]})))
# [2696.09601899 3978.59717296]

Y = reg.predict(X)
fig, axs = plt.subplots(1, 1, tight_layout=True)
axs.scatter(X['x'], y, color='blue')
axs.scatter(X['x'], Y, color='red')
fig.tight_layout()
plt.show()
```

**Comment by qbphilip** [comment]
Thanks Nick for the example!

Packed it into a unit test and fixed it.
It was a problem with the Layer normalisation (which was not learning the parameters but using the sample mean/var)

Merged a fix into dev and will aim to release this week (NeurIPS week haha). In the meantime try installing from GitHub.

**Comment by qbphilip** [comment]
Pushed another fix, the LayerNorm allowed leakage of "unmasked" variables.

We are trying to release later today :)
