### ISSUE TITLE
Can't find sklearn interface tutorial

### ISSUE THREAD

**Issue by nick-gorman** [quantumblacklabs/causalnex#80]
This may just be user error,  but I can't seem to find the sklearn interface tutorial on readthedocs anymore.

**Comment by nick-gorman** [comment]
I found a link to the tutorial using a search engine, but it appears to not be rendering properly.

https://causalnex.readthedocs.io/en/latest/03_tutorial/sklearn_tutorial.html

**Comment by qbphilip** [comment]
Thanks for reporting, the docs might have not updated with the release?!

Will look into it.

@mzjp2 Did you notice something in the CD pipeline?

**Comment by mzjp2** [comment]
Super sorry, working on a fix ASAP - thanks for reporting!

**Comment by mzjp2** [comment]
Fixed in https://github.com/quantumblacklabs/causalnex/commit/45897a48646851afb35199f1635bc274191b07c2 -- your link should work now :)
