### ISSUE TITLE
Domain expertise and DAGRegressor

### ISSUE THREAD

**Issue by nick-gorman** [quantumblacklabs/causalnex#81]
Is there a way to use domain expertise with the DAGRegressor? For example, by constraining two variables to not be causally linked,  or by specify directional causal relationships between variables.

**Comment by qbphilip** [comment]
Hey Nick!

Yes, you can. We call them "tabu"-edges/parents/children.
You can only specify independence, "forcing" dependence between variables is not possible.

Look at the documentation of these arguments:
```
tabu_edges: List = None,
tabu_parent_nodes: List = None,
tabu_child_nodes: List = None,
```

Philip

**Comment by nick-gorman** [comment]
Thanks Philip!
