### ISSUE TITLE
Pygraphviz does not run with Causalnex

### ISSUE THREAD

**Issue by rafmora** [quantumblacklabs/causalnex#82]
## Description
I am trying to reproduce the tutorial https://causalnex.readthedocs.io/en/latest/03_tutorial/03_tutorial.html
However, the errors appear when trying to plot using pygraphviz (regardless of the method used for install it either pip or conda)

## Context
The graph did not reproduce 

## Steps to Reproduce
run 
from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE

viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))

ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')

## Expected Result
no graph

## Actual Result
Successfully installed causalnex-0.9.0 pgmpy-0.1.12 prettytable-0.7.2 scikit-learn-0.22.2 wrapt-1.11.2
Collecting pygraphviz
  Downloading https://files.pythonhosted.org/packages/1e/19/acf3b8dbd378a2b38c6d9aaa6fa9fcd9f7b4aea5fcd3460014999ff92b3c/pygraphviz-1.6.zip (117kB)
     |████████████████████████████████| 122kB 5.3MB/s 
Building wheels for collected packages: pygraphviz
  Building wheel for pygraphviz (setup.py) ... error
  ERROR: Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: pygraphviz
    Running setup.py install for pygraphviz ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i72x5xfb/pygraphviz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i72x5xfb/pygraphviz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eirx_jca/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

```
## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): causalnex 0.8.1
* Python version used (`python -V`): python version 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
* Operating system and version: windows 10

**Comment by Acruve15** [comment]
Try installing`pygraphviz` with `conda install graphviz pygraphviz -c alubbock`

reference: https://github.com/pygraphviz/pygraphviz/issues/186

**Comment by mzjp2** [comment]
Closing this as stale - there might be some helpful instructions over at https://github.com/quantumblacklabs/causalnex/issues/90 - feel free to open a new issue if you're still having trouble.
