### ISSUE TITLE
Enforce add_edge on DAGRegressor

### ISSUE THREAD

**Issue by pabloazurduy** [quantumblacklabs/causalnex#83]
Hi I have a regression problem similar to the `Boston Housing` and I followed the [Sklearn tutorial](https://causalnex.readthedocs.io/en/latest/03_tutorial/sklearn_tutorial.html)
I've also followed the [basic bn tutorial](https://causalnex.readthedocs.io/en/latest/03_tutorial/03_tutorial.html) where the NOTEARS result is debugged and improved removing edges and *enforcing* others 
```
sm.add_edge("failures", "G1")
sm.remove_edge("Pstatus", "G1")
sm.remove_edge("address", "G1")

```
Is there a similar feature for the `DAGRegressor.__init__`  method?, or I have a conceptual error ?
I've tried to follow also the [Distribution Schema Tutorial](https://causalnex.readthedocs.io/en/latest/03_tutorial/dist_schema_tutorial.html) but I never understood how to fit the final model to get the distributions values. using `causalnex.network.BayesianNetwork`seems like It shouldn’t work (because all the variables are continuous)

could someone provide me some guidance on this ! many thanks !

**Comment by qbphilip** [comment]
Hello,

Thanks for your question!

The `StructureModel` is stored in the DAGRegressor object as an attribute after fitting (following sklearn norms):
```
sm = model.graph_
sm.add_edge("failures", "G1")
sm.remove_edge("Pstatus", "G1")
sm.remove_edge("address", "G1")
```
Since a `StructureModel` inherits `nx.DiGraph` you can also use other functionality from networkx directly!

Does this answer your question?

**Comment by oentaryorj** [comment]
Covered in the latest version of https://causalnex.readthedocs.io/en/latest/03_tutorial/sklearn_tutorial.html, i.e., `model.graph_`
