### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by sriharsha0806** [quantumblacklabs/causalnex#9]
## Description
I am currently running Bayesian Network Tutorial. I am getting the following syntax error while running the code.

## Context
How has this bug affected you? What were you trying to accomplish?
Building a Bayesian Network. Unable to build it because of the syntax error.

## Steps to Reproduce
from causalnex.structure import StructureModel
# Encoding the causal graph suggested by an expert
#        d
#     ↙  ↓  ↘
#    a ← b → c
#        ↑  ↗
#        e
sm_manual = StructureModel()
sm_manual.add_edges_from(
    [
        ("b", "a", origin="expert"),
        
    ]
)

Run it in jupyter

## Expected Result
It should form a Bayesian Graph

## Actual Result
Getting syntax Error

```
-- If you received an error, place it here.
 File "<ipython-input-5-127b20ebb195>", line 11
    ("b", "a", origin="expert"),
                     ^
SyntaxError: invalid syntax
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): 0.4.2
* Python version used (`python -V`): 3.7.4
* Operating system and version: Ubuntu 18.04

**Comment by ZainPatelQB** [comment]
Cleaning up your code block, it looks like you're doing

```python
sm_manual.add_edges_from([("b", "a", origin="expert")])
```

but it should be (i.e: the `origin` kwarg should be a kwarg, not a member of the tuple.

```python
sm_manual.add_edges_from([("b", "a")], origin="expert")
```

Does that work?

**Comment by SteveLerQB** [comment]
Yes, there's an error in the code snippet in the user guide https://causalnex.readthedocs.io/en/latest/04_user_guide/04_user_guide.html
 
Just created a pull request to fix this 🙂 
https://github.com/quantumblacklabs/causalnex/pull/10

**Comment by sriharsha0806** [comment]
@ZainPatelQB @SteveLerQB continuation of the tutorial, I have defined structure Model as

```
from causalnex.structure import StructureModel
# Encoding the causal graph suggested by an expert
#        d
#     ↙  ↓  ↘
#    a ← b → c
#        ↑  ↗
#        e
sm_manual = StructureModel()
sm_manual.add_edges_from(
    
    [
        ("b","a"),
        ("b","c"),
        ("d","a"),
        ("d","c"),
        ("d","b"),
        ("e","c"),
        ("e","b"),
    ],     
    
    
    origin="expert",  
    
)
```

I am using struct_data from previous causalnex tutorial. 

````
from causalnex.structure.notears import from_pandas
from causalnex.network import BayesianNetwork
# Unconstrained learning of the structure from data
sm = from_pandas(struct_data)
# Imposing edges that are not allowed in the causal model
sm_with_tabu_edges = from_pandas(struct_data, tabu_edges=[("e", "a")])
# Imposing parent nodes that are not allowed in the causal model
sm_with_tabu_parents = from_pandas(struct_data, tabu_parent_nodes=["a", "c"])
# Imposing child nodes that are not allowed in the causal model
sm_with_tabu_parents = from_pandas(struct_data, tabu_child_nodes=["d", "e"])
```
When I ran the code I got the following KeyError,

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-cc0c03133d3a> in <module>
      4 sm = from_pandas(struct_data)
      5 # Imposing edges that are not allowed in the causal model
----> 6 sm_with_tabu_edges = from_pandas(struct_data, tabu_edges=[("e", "a")])
      7 # Imposing parent nodes that are not allowed in the causal model
      8 sm_with_tabu_parents = from_pandas(struct_data, tabu_parent_nodes=["a", "c"])

~/miniconda3/lib/python3.7/site-packages/causalnex/structure/notears.py in from_pandas(X, max_iter, h_tol, w_threshold, tabu_edges, tabu_parent_nodes, tabu_child_nodes)
    241 
    242     if tabu_edges:
--> 243         tabu_edges = [(col_idx[u], col_idx[v]) for u, v in tabu_edges]
    244     if tabu_parent_nodes:
    245         tabu_parent_nodes = [col_idx[n] for n in tabu_parent_nodes]

~/miniconda3/lib/python3.7/site-packages/causalnex/structure/notears.py in <listcomp>(.0)
    241 
    242     if tabu_edges:
--> 243         tabu_edges = [(col_idx[u], col_idx[v]) for u, v in tabu_edges]
    244     if tabu_parent_nodes:
    245         tabu_parent_nodes = [col_idx[n] for n in tabu_parent_nodes]

KeyError: 'e'

In this tutorial, data variable mentioned in the cell isn't provided. What should the data variable be?

**Comment by SteveLerQB** [comment]
Dear @sriharsha0806,

Thanks for your question. Each of your data variable should have numerical rows. Let me give you a simple example for this.

```
from causalnex.structure import StructureModel
import numpy as np
import pandas as pd
from causalnex.structure.notears import from_pandas
from causalnex.plots import plot_structure

a = np.random.normal(0, 1, 200)
b = 5 + 3 * a
c = -6 * a
d = 10 * b
struct_data = pd.DataFrame({"a": a, "b": b, "c": c, "d": d})
sm = from_pandas(struct_data, w_threshold=0.5)
plot_structure(sm)
```

This will give you the following plot:

![image1](https://user-images.githubusercontent.com/55385183/73957557-6d3f9d00-48fe-11ea-97d8-0f70a855fa6b.png)

But you may also think that there should not be any relationship between the data variable "a" and "c". You can do the following:

`sm = from_pandas(struct_data, w_threshold=0.5, tabu_edges=[("a", "c")])
plot_structure(sm)`

and you will obtain this plot:

![image2](https://user-images.githubusercontent.com/55385183/73958327-ab898c00-48ff-11ea-9f7c-e4ef1bdddd27.png)

I hope this helps! 🙂

**Comment by sriharsha0806** [comment]
@SteveLerQB Thanks for the explanation
