### ISSUE TITLE
Installation Docs have an example of installing Python 3.8

### ISSUE THREAD

**Issue by AdrianAntico** [quantumblacklabs/causalnex#90]
## Description
Change your installation docs to have an example of installing a version of Python that is compatible with this module.

## Context
If the software is made for Python 3.5, 3.6, or 3.7 then the installation examples shouldn't show someone how to install Python 3.8

## Possible Implementation
Change the 3.8 to 3.5,6, or 7. 

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by mzjp2** [comment]
Causalnex 0.9 onwards should be Python 3.6, 3.7 and 3.8 as far as I know. Where did you see Python 3.5/6/7 referenced?

**Comment by AdrianAntico** [comment]
@mzjp2 Thanks for the quick reply! It's in the Frequently Asked Questions. Also, pygraphviz isn't available for Python 3.8. When I tried running it it suggested an alternative way to print the graph but I couldn't get that to work. Now I'm wondering if I should just install Python 3.7 to bypass that issue.

## What version of Python does CausalNex use?

CausalNex is built for Python 3.5, 3.6 and 3.7.

**Comment by mzjp2** [comment]
> @mzjp2 Thanks for the quick reply! It's in the Frequently Asked Questions.

We completely forgot to update that section - bad grepping skills! Thanks for pointing out, we'll get it fixed ASAP.

I had a look at https://pypi.org/project/pygraphviz/ and it seems to be supported on Python 3.8 (at least version 1.6 is).

**Comment by AdrianAntico** [comment]
I didn't have any luck installing it. I'm switching to 3.7.9 for now. I'm mostly looking to test out your module on a particular use-case. I can always revisit the python versioning down the road.

Thanks for the quick replies though!

**Comment by mzjp2** [comment]
Ah, sorry you couldn't get it to work :(

No worries, thanks for testing out CasalNex and opening the issue. Feel free to engage whenever!

**Comment by AdrianAntico** [comment]
Turns out installing python 3.7.9 didn't enable me to install pygraphviz either. Looks like most of their open issues are about installation. I don't recall seeing examples that utilize something other than pygraphviz (please point me to one if they exist) and if they aren't there could the examples include alternative graphing methods?

**Comment by mzjp2** [comment]
> Turns out installing python 3.7.9 didn't enable me to install pygraphviz either. Looks like most of their open issues are about installation. I don't recall seeing examples that utilize something other than pygraphviz (please point me to one if they exist) and if they aren't there could the examples include alternative graphing methods?

Is this useful? https://causalnex.readthedocs.io/en/latest/03_tutorial/plotting_tutorial.html#Alternative-solutions

**Comment by AdrianAntico** [comment]
@mzjp2  I was able to get pygraphviz installed. I conversed with the package creator and he gave me some steps to follow that worked. 

1. Needed to have visual cpp build tools. Can find here: https://visualstudio.microsoft.com/visual-cpp-build-tools/
2. Restart server after installing
3. git clone https://github.com/pygraphviz/pygraphviz.git
4. Open PowerShell and cd to pygraphviz
5. If your graphviz folder has the version in the name, remove it so it's just Graphviz
6. In PowerShell, run:
$PATH = [Environment]::GetEnvironmentVariable("PATH")
$graphviz_path = "C:\Program Files\Graphviz\bin
[Environment]::SetEnvironmentVariable("PATH", "$graphviz_path; $PATH")
python -m pip install --upgrade pip wheel setuptools
python -m pip install -r requirements/test.txt
python -m pip install --global-option=build_ext `
  --global-option="-IC:\Program Files\Graphviz\include" `
  --global-option="-LC:\Program Files\Graphviz\lib" `
  .
python -m pip list

**Comment by mzjp2** [comment]
Amazing, thanks for sharing back here and helping anybody else with a similar issue. This could potentially go into our docs as a how-to for Windows (it's _very_ tricky getting PyGraphViz to work on Windows, as you've found)

**Comment by AdrianAntico** [comment]
The author stated that in a future release it should be easier but just in case it isn't, there's always the method above. Feel free to add it to the docs. When I go to repo to test something out, I like to see the help needed to install challenging dependencies.

**Comment by AdrianAntico** [comment]
Also, I have a really interesting use case I'm taking on that will end up relying on some sort of pgm. Let me know if you're interested in what I'm looking to do as it might lead to potential enhancement and innovation opportunities.

**Comment by mzjp2** [comment]
Ooh, absolutely! @qbphilip may also be interested here :)

**Comment by AdrianAntico** [comment]
Shoot me an email at adrianantico@gmail.com
