### ISSUE TITLE
Racial discrimination in the 'B' feature of the Boston housing dataset

### ISSUE THREAD

**Issue by jj-jr** [quantumblacklabs/causalnex#92]
## Description
[As](https://github.com/quantumblacklabs/causalnex/issues/91) [others](https://github.com/scikit-learn/scikit-learn/issues/16155) [have](https://github.com/salesforce/TransmogrifAI/issues/493) [pointed out](https://github.com/scikit-learn/scikit-learn/pull/18594), the `load_boston` dataset has the problematic 'B' feature which discriminates against black folk by adjusting prices of houses according to the black population. 

Since the original post was submitted on January 18th of last year, I'd mostly like to check on the status of this dataset replacement and see how I can help.

**Comment by qbphilip** [comment]
Hello @ii-jr, 

Its high on my TODO list but I am wrapping up a project at the moment.
If you have capacity, I would welcome your contribution, the notebook in question is located at `docs/source/03_tutorial/sklearn_tutorial.ipynb`.

As mentioned in #91 , we are planning to do more than the simple replacement but one step at a time.
Do you have a suggestion for a replacement dataset for regression with several features, e.g. `diabetes`?

**Comment by koaning** [comment]
@jj-jr the `B` columns is actually [even more messed up](https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8) than you might originally think.

**Comment by qbphilip** [comment]
See #91 for details
