### ISSUE TITLE
Using Pandas >1.0.0 AttributeError: 'DataFrame' object has no attribute 'ix'<Title>

### ISSUE THREAD

**Issue by rafmora** [quantumblacklabs/causalnex#93]
## Description
Causalnex does not run using Pandas>=1.0.0 using the fit_cpds()
bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")
## Context
While running the causalnex tutorial https://causalnex.readthedocs.io/en/latest/03_tutorial/03_tutorial.html 

## Steps to Reproduce
Fit Conditional Probability Distributions
The fit_cpds method of BayesianNetwork accepts a dataset to learn the conditional probablilty distributions (CPDs) of each node, along with a method of how to do this fit.
bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")
## Expected Result
Fit conditional probability distributions.

## Actual Result
Pandas newer version did not allow causalnex fit_cpds() to work

```
-- If you received an error, place it here.
 AttributeError: 'DataFrame' object has no attribute 'ix'<Title>


* CausalNex version used (`pip show causalnex`): 0.8.1
* Python version used (`python -V`): 3.7.9
* Operating system and version: Microsoft Windows 10

**Comment by mzjp2** [comment]
> * CausalNex version used (`pip show causalnex`): 0.8.1

I believe this is expected. CausalNex 0.8.1 has `pandas>=0.24, <1.0` as a requirement.

Can you upgrade to CausalNex 0.9.0 or 0.9.1 when the requirement was relaxed to `pandas>=1.0` and see if the error still holds?

**Comment by rafmora** [comment]
Thanks. It worked. Very appreciated.
Take care,
RAFA

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2021 at 5:10 PM, Zain Patel<notifications@github.com> wrote:   


   
   - CausalNex version used (pip show causalnex): 0.8.1


I believe this is expected. CausalNex 0.8.1 has pandas>=0.24, <1.0 as a requirement.

Can you upgrade to CausalNex 0.9.0 or 0.9.1 when the requirement was relaxed to pandas>=1.0 and see if the error still holds?
