### ISSUE TITLE
Question on Causal Effect Heterogeneity output

### ISSUE THREAD

**Issue by cesarteaser** [quantumblacklabs/causalnex#95]
Hello,
I was curious to understand if CausalNex can provide outputs on the Heterogeneity effect. 

For example, Instead of saying **"ON AVERAGE an ad causes some quantified uplift in sales across all folks in my dataset"**, can it say "**this ad WORKS BEST on a specific sub-group of my dataset (i.e. Millenials with 1 pet in the household)"**?

If so, can you point me to the code which would produce such output, please? Thanks a ton.

**Comment by oentaryorj** [comment]
Thanks for the question. I believe this is currently not supported in CausalNex. However, if you have any suggestion, we are happy to hear! Contributions are welcome as well.

Closing this issue for now. Feel free to raise a new issue or pull request should you have an idea.
