### ISSUE TITLE
ValueError: The cpd states do not match expected states: expected {0, 1}, found {'yes', 'no'}

### ISSUE THREAD

**Issue by rafmora** [quantumblacklabs/causalnex#96]
## Description
Thank YOU guys for the good work in developing this excellent API. Very useful
I ran the tutorial https://causalnex.readthedocs.io/en/latest/03_tutorial/03_tutorial.html, but I am getting an error. I do not know what I am not doing correctly.

## Context
Tutorial 

## Steps to Reproduce
steps from the tutorial

## Expected Result
the cps is expecting states 0,1; but it sees Yes, No

## Actual Result
Stops when running
print("distribution before do", ie.query()["higher"])
ie.do_intervention("higher",
                   {'yes': 1.0,
                    'no': 0.0})
print("distribution after do", ie.query()["higher"])

-- If you received an error, place it here.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-58-5bc257bb265b> in <module>
      2 ie.do_intervention("higher",
      3                    {'yes': 1.0,
----> 4                     'no': 0.0})
      5 print("distribution after do", ie.query()["higher"])

C:\ProgramData\Anaconda3\lib\site-packages\causalnex\inference\inference.py in do_intervention(self, node, state)
    211             state = {s: float(s == state) for s in self._cpds[node]}
    212 
--> 213         self._do(node, state)
    214         self._generate_bbn()
    215 

C:\ProgramData\Anaconda3\lib\site-packages\causalnex\inference\inference.py in _do(self, observation, state)
    173                 "The cpd states do not match expected states: expected {expected}, found {found}".format(
    174                     expected=set(self._cpds_original[observation]),
--> 175                     found=set(state.keys()),
    176                 )
    177             )

ValueError: The cpd states do not match expected states: expected {0, 1}, found {'yes', 'no'}
-- Separate them if you have more than one.
```

## Your Environment


* CausalNex version used 0.9.1
* Python version used (`python -V`): Python 3.7.9
* Operating system and version: Windows 10

**Comment by PNEPNE** [comment]
Hi @rafmora,
I tried to run this recently and the output looks alright on my machine (see screenshot below).
If you are running from a Jupyter notebook, perhaps you can try to restart the kernel and re-run? It might also be worth reinstalling/upgrading python and CausalNex just in case.
PS (For benefit of anyone else reading through this): Please refer tutorial for full code - https://causalnex.readthedocs.io/en/stable/03_tutorial/03_tutorial.html
![issue 96](https://user-images.githubusercontent.com/78932705/128060285-4025390f-0a76-400b-bbac-68e72eb55b65.JPG)

**Comment by oentaryorj** [comment]
Closing this issue as the do-intervention seems to be working fine, as per @PNEPNE's example. Feel free to raise a new issue if the problem persists. Thank you.
