### ISSUE TITLE
[generate_binary_dataframe] how does it work?

### ISSUE THREAD

**Issue by LukaJakovljevic** [quantumblacklabs/causalnex#97]
### Question
Hello,
I am trying to understand how `causalnex.structure.data_generators.generate_binary_dataframe` ([docs](https://causalnex.readthedocs.io/en/latest/source/api_docs/causalnex.structure.data_generators.generate_binary_dataframe.html#causalnex.structure.data_generators.generate_binary_dataframe)) synthesizes binary time series. I see that it does it by calling `causalnex.structure.data_generators.sem_generator` ([docs](https://causalnex.readthedocs.io/en/latest/source/api_docs/causalnex.structure.data_generators.sem_generator.html#causalnex.structure.data_generators.sem_generator)). I would appreciate if you can shortly explain what is the intuition/logic behind assigning new time series values, how in fact sem_generators does it? I was trying to understand, so maybe others find it useful. Thank you in advance!

P.S. Seems the latter has a mistake in example in docs and also in comment in source code:
instead of `noise_scale=1` should stand `noise_std = 1`

cc: @qbphilip, @GabrielAzevedoFerreiraQB, @pjbqb

**Comment by boxinqb** [comment]
Hi @LukaJakovljevic , thanks for the reminder and the great question!

We first create a weight matrix capturing the relationship between parent nodes and child nodes. Next we sample the dataframe node by node (sample the child node depending on its parent nodes). For each sampling of a child node, `sem_generator` is calling `_sample_binary_from_latent` to generate the binary values for that node. Essentially what it is trying to do is to compare the latent mean with 0 as the default threshold when assigning values. To prevent a skewed distribution being generated, `max_imbalance` is used to compare with the proportion of positive values obtained above and latent mean would now be compared with a new threshold (the quantile position specified by `max_imbalance`) before assigning values. And finally, this would have the imbalance proportion within accepted range. 

Please note that this method is meant for sampling from a traditional Bayesian Network. If you would like to generate values based on Dynamic Bayesian Network - please look into `causalnex.structure.data_generators.wrapper.generate_dataframe_dynamic`.

Hope this clarifies! :)

**Comment by boxinqb** [comment]
Hi @LukaJakovljevic , thanks for the reminder and the great question!

We first create a weight matrix capturing the relationship between parent nodes and child nodes. Next we sample the dataframe node by node (sample the child node depending on its parent nodes). For each sampling of a child node, sem_generator is calling _sample_binary_from_latent to generate the binary values for that node. Essentially what it is trying to do is to compare `latent_mean` with 0 as the default threshold when assigning values. To prevent a skewed distribution being generated, `max_imbalance` is then used to compare with the proportion of positive values obtained above and `latent_mean` would now be compared with a new threshold (the quantile position specified by `max_imbalance`) before assigning values. And finally, this would have the imbalance proportion within accepted range.

Please note that this method is meant for sampling from a traditional Bayesian Network. If you would like to generate values based on Dynamic Bayesian Network - please look into causalnex.structure.data_generators.wrapper.generate_dataframe_dynamic.

Hope this clarifies! :)

**Comment by boxinqb** [comment]
Hi @LukaJakovljevic , thanks for the reminder and the great question!

We first create a weight matrix capturing the relationship between parent nodes and child nodes. Next we sample the dataframe node by node (sample the child node depending on its parent nodes). For each sampling of a child node, `sem_generator` is calling `_sample_binary_from_latent` to generate the binary values for that node. Essentially what it is trying to do is to compare `latent_mean` with 0 as the default threshold when assigning values. To prevent a skewed distribution being generated, `max_imbalance` is then used to compare with the proportion of positive values obtained above and `latent_mean` would now be compared with a new threshold (the quantile value specified by `max_imbalance`) before assigning values. And finally, this would have the imbalance proportion within accepted range.

Please note that this method is meant for sampling from a traditional Bayesian Network. If you would like to generate values based on Dynamic Bayesian Network - please look into `causalnex.structure.data_generators.wrapper.generate_dataframe_dynamic`.

Hope this clarifies! :)
