### ISSUE TITLE
Question on arrow directions

### ISSUE THREAD

**Issue by TPreece101** [quantumblacklabs/causalnex#98]
Hello,

Thanks for all the time that you guys have put into this - it is a great package and the docs are fantastic.

I have a question about usage/something that doesn't make sense to me.

So I am experimenting with the UCI Bank Marketing dataset found here: https://archive.ics.uci.edu/ml/datasets/Bank+Marketing

It is a simple dataset describing whether a marketing campaign was successful with features about the campaign and about the targeted people.

Running the NOTEARS algorithm I get the 'age' as being the child node of quite a few edges. For example there is an edge from 'balance' -> 'age'. Now we know that a bank balance can't cause people to age. Since nothing in the dataset should cause 'age' I added it in the 'tabu_child_nodes' argument.

Adding this causes no relationships with 'age' to be found - even though there are some correlations between 'age' and other things such as 'balance'. This doesn't make sense to me - I was expecting some of the arrows to just be flipped.

Am I missing something?

If I think there should be a relationship the other way e.g. 'age' -> 'balance' (people have higher bank balances when they are older) should I just flip the arrow myself instead of adding the constraint?

Code to reproduce: 
```py
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, scale
from causalnex.structure.notears import from_pandas
from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE

import warnings
warnings.filterwarnings("ignore")

# read data
data = pd.read_csv('bank.csv', sep=';')
print(data.shape)
data.head()

struct_data = data.copy()

# encode categorical variables
non_numeric_columns = list(struct_data.select_dtypes(exclude=[np.number]).columns)
print(non_numeric_columns)

le = LabelEncoder()
for col in non_numeric_columns:
    struct_data[col] = le.fit_transform(struct_data[col])

struct_data.head(5)

# rescale large columns - seems to speed it up a lot
rescale_columns = ['balance', 'duration', 'pdays']
for col in rescale_columns:
  struct_data[col] = scale(struct_data[col])

# initial structure learning
sm = from_pandas(
    struct_data,
    w_threshold=0.8
)

viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))

# structure learning with age as a forbidden child node
sm = from_pandas(
    struct_data,
    w_threshold=0.8,
    tabu_child_nodes=['age']
)

viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))
```

**Comment by PNEPNE** [comment]
``Hi @TPreece101 ,
**Short answer: Yes- you can flip the arrow based on domain knowledge.**

The graph shows that the strongest conditional dependencies are present between these variables, given this data.
While, it can give a good starting point quickly, NOTEARS is not a causal algorithm. Causal structure should be validated based on domain knowledge.
Feel free to use parameters like _'W-Threshold'_ , _'beta'_ (in _from_pandas_lasso_) and data preprocessing (e.g. scaling, discretizing, encoding etc.) to get a graph which needs minimum number of changes based on domain knowledge.

Post a few iterations, I got the graph below-
![graph_vS](https://user-images.githubusercontent.com/78932705/128063179-3b8b63eb-da6a-443b-8498-9f26ffc3ed41.JPG)
**Full code to replicate this-**
`import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, scale
from causalnex.structure.notears import from_pandas,from_pandas_lasso
from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
import warnings
warnings.filterwarnings("ignore")
# read data
data = pd.read_csv('bank.csv', sep=';')
print(data.shape)
data.head()
struct_data = data.copy()

# encode categorical variables
non_numeric_columns = list(struct_data.select_dtypes(exclude=[np.number]).columns)
print(non_numeric_columns)
le = LabelEncoder()
for col in non_numeric_columns:
    struct_data[col] = le.fit_transform(struct_data[col])
# using discretizer on unscaled data
from causalnex.discretiser import Discretiser
from sklearn.preprocessing import StandardScaler

from causalnex.discretiser.discretiser_strategy import (
    DecisionTreeSupervisedDiscretiserMethod,
)
features = list(data.columns.difference(['y']))
tree_discretiser = DecisionTreeSupervisedDiscretiserMethod(
    mode="single", 
    tree_params={"max_depth": 2, "random_state": 2021},
)
tree_discretiser.fit(
    feat_names=features, 
    dataframe=struct_data, 
    target_continuous=False,
    target="y",
)

for col in features:
    struct_data[col] = tree_discretiser.transform(struct_data[[col]])
struct_data.head()

tree_discretiser.map_thresholds

# rescale
rescale_columns = ['balance', 'duration', 'pdays']
for col in rescale_columns:
  struct_data[col] = scale(struct_data[col])

# structure learning with age as a forbidden child node
sm = from_pandas_lasso(
    struct_data,
    w_threshold=0.35,
    beta=0.001,
    tabu_child_nodes=['age']
)
viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))`

**Comment by TPreece101** [comment]
Thanks for the response - that makes sense. In what circumstances would you recommend using `from_pandas_lasso` instead of `from_pandas` ?

**Comment by oentaryorj** [comment]
My understanding is that `from_pandas_lasso` incorporates L1-regularisation, which fosters _sparsity_ in the adjacency weight W. So in theory `from_pandas_lasso` would be more suitable in situations where we have a large number of nodes (variables) and we are interested in learning a sparse directed acyclic graph (DAG). Having said that, `from_pandas_lasso` may not necessarily give better results than `from_pandas` - this would very much depend on the data.

For more information, you may want to refer to this article - https://papers.nips.cc/paper/2018/file/e347c51419ffb23ca3fd5050202f9c3d-Paper.pdf

**Comment by TPreece101** [comment]
Thanks a lot for your responses @oentaryorj
