### ISSUE TITLE
Assign known cpds to Bayesian Network

### ISSUE THREAD

**Issue by jssimon01** [quantumblacklabs/causalnex#99]
## Description
I would like to directly assign known cpds to my Bayesian Network with out performing a fitting procedure."

## Context
In some situations the cpds may already be known, or I would like to force them to match known cpds from some other problem. Once cpds have been fit it already seems possible to reassign them to a new value. The problem is if I have a new Bayesian network I can not seem to find a way to assign the original values. For example if my Bayesian network is named bn, and it has a node "A", and I have a know conditional probability distribution in  dataframe cpd, when I try to assign bn.cpds["A"] = cpd I find that bn.cpds remains empty. Is there already a simple way to do this and I am just not doing it correctly.

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by oentaryorj** [comment]
A new function `set_cpd` has been implemented in [this commit](https://github.com/quantumblacklabs/causalnex/commit/6031e1a6978c083515f8ddbc0a11e05e91c0a115) and will be made available in the next release.
